databases:
  - name: dpg-ccek4t6n6mpt4gqt7ssg-a
    databaseName: rendertestdb
    user: rendertestdb_user

services:
  - type: web
    name: renderTest
    env: python
    buildCommand: 'pip install -r requirements.txt'
    startCommand: "gunicorn renderTest.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: rendertestdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4